name: sugar
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc_pattern: 2.5.1
  flutter_masked_text: 0.8.0              # Aplica Máscara no campo
  path_provider: 1.5.1                    # Package para localizar pastas comuns do dispositivo
  rxdart: 0.22.6
  dio: 3.0.8                              # Cliente Web que suporta Download de arquivos
  datetime_picker_formfield: 1.0.0        # Seletor de hora
  flutter_cupertino_localizations: 1.0.1  # Localização do App, ajuda a definir o idioma
  encrypt: 4.0.0                          # API de criptografia
  awesome_dialog: 0.1.0                   # Botoes flutuantes estilizados
  connectivity: 0.4.6+1                   # Verifica conectividade do aparelho, diferencianddo entre rede padrão ou Wifi
  signature: 2.0.1                        # Assinatura na tela
  uuid: 2.0.4                             # Gerador de UUID
  flutter_i18n: 0.8.3                     # Acessa arquivo JSON com traduções, baseado na localização
  month_picker_dialog: 0.3.0              # Seletor de data


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.8+2         # Splash Image de intro
  json_annotation: ^3.0.0                 # Gera arquivos JSON para salvar Break Bulk e os Containers
  build_runner: ^1.7.1                    # Facilitar a importação e exportação de pacotes extras
  json_serializable: ^3.2.3               # Serialização dos arquivos JSON

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_inicial.png"

# - Documentação do splash: https://pub.dev/packages/flutter_native_splash#-readme-tab-
flutter_native_splash:
  image: assets/images/logo_afl_nova.png
  color: 504F51

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/i18n/
    #- assets/jsonSugar.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
